### ISSUE TITLE
Use IoC/DI for nextjs

### ISSUE THREAD

**Issue by binkoni** [nugurang/nugurang-front#4]
Use IoC/DI for nextjs

**Comment by snapperbay4453** [comment]
조사 결과, 프론트엔드 분야에서 제어 반전 및 의존성 주입이 백엔드에 필적하게 많이 사용되지는 않는 것 같습니다.
다만 관련 라이브러리가 이미 존재하는 것으로 보아서 적용 자체는 가능한 것으로 보이며,
추후 이를 사용할 만한 상황이 발생했을 시 적용을 고려하도록 하는 것이 좋겠습니다.
